In [1]:
import numpy as np

def convolve2d(input_matrix, kernel, bias=0.0):
    # Get dimensions
    input_height, input_width = input_matrix.shape
    kernel_height, kernel_width = kernel.shape
    
    # Calculate output dimensions
    output_height = input_height - kernel_height + 1
    output_width = input_width - kernel_width + 1
    
    # Initialize output matrix
    output = np.zeros((output_height, output_width))
    
    # Perform convolution
    for y in range(output_height):
        for x in range(output_width):
            output[y, x] = np.sum(input_matrix[y:y+kernel_height, x:x+kernel_width] * kernel) + bias
    
    # Apply ReLU activation
    output = np.maximum(output, 0)
    
    return output

# Define the input matrix
input_matrix = np.array([
    [0.26775, 0.26775, 0.1905,  0.11325, 0.18825, 0.202,   0.21775, 0.241,   0.263, 0.263],
    [0.26775, 0.26775, 0.1905,  0.11325, 0.18825, 0.202,   0.21775, 0.241,   0.263, 0.263],
    [0.1795,  0.1795,  0.074,   0.167,   0.177,   0.17675, 0.1765,  0.1765,  0.168, 0.168],
    [0.04725, 0.04725, 0.1705,  0.17325, 0.17325, 0.173,   0.173,   0.1495,  0.05425, 0.05425],
    [0.1335,  0.1335,  0.17175, 0.17075, 0.17025, 0.16975, 0.17025, 0.07425, 0.06175, 0.06175],
    [0.13875, 0.13875, 0.1775,  0.1745,  0.17175, 0.16925, 0.16175, 0.02275, 0.07025, 0.07025],
    [0.19775, 0.19775, 0.18575, 0.18225, 0.179,   0.17575, 0.15475, 0.024,   0.15025, 0.15025],
    [0.20225, 0.20225, 0.19475, 0.1905,  0.187,   0.18325, 0.147,   0.15325, 0.202, 0.202],
    [0.19975, 0.19975, 0.1995,  0.198,   0.19575, 0.19225, 0.19425, 0.199,   0.19875, 0.19875],
    [0.19975, 0.19975, 0.1995,  0.198,   0.19575, 0.19225, 0.19425, 0.199,   0.19875, 0.19875]
])

# Define all 3 filters from your first conv layer
filters = [
    np.array([  # Filter 1
        [ 0.6113,  0.1495,  0.2552],
        [ 0.8015, -0.0844,  0.3424],
        [ 0.2729,  0.5057,  0.4225]
    ]),
    np.array([  # Filter 2
        [-0.1432,  0.3289,  0.7478],
        [ 0.3035,  0.2921,  0.6258],
        [ 0.4233,  0.1216,  0.225 ]
    ]),
    np.array([  # Filter 3
        [-0.9974, -0.2162, -0.1352],
        [-0.9869, -0.4596,  0.0533],
        [-0.588,  -0.518,   0.1744]
    ])
]

# Bias terms from your model (asumiendo que son ceros ya que no se muestran en el output)
biases = [0.0, 0.0, 0.0]

print("=== Convolution Results ===")
print("Input shape:", input_matrix.shape)
print("\n=== Activations for each filter ===")

for i, (kernel, bias) in enumerate(zip(filters, biases)):
    result = convolve2d(input_matrix, kernel, bias)
    
    print(f"\nFilter {i+1}:")
    print(np.round(result, 4))  # Redondeado a 4 decimales como en tu output
    print(f"Max value: {np.max(result):.4f}")
    print(f"Min value: {np.min(result):.4f}")

=== Convolution Results ===
Input shape: (10, 10)

=== Activations for each filter ===

Filter 1:
[[0.6806 0.6153 0.5684 0.5027 0.6215 0.6556 0.6889 0.7189]
 [0.5152 0.5882 0.4946 0.5363 0.5961 0.6026 0.5661 0.5297]
 [0.4242 0.4416 0.5019 0.5615 0.5674 0.5185 0.4319 0.3873]
 [0.417  0.4509 0.5651 0.5626 0.5571 0.4545 0.3786 0.2602]
 [0.5381 0.5317 0.5788 0.571  0.5548 0.4143 0.4006 0.2527]
 [0.596  0.5953 0.6017 0.5907 0.559  0.4586 0.4966 0.3297]
 [0.6494 0.6451 0.6278 0.6169 0.5926 0.5584 0.5482 0.4892]
 [0.6549 0.6515 0.6427 0.6334 0.6191 0.6137 0.6089 0.625 ]]
Max value: 0.7189
Min value: 0.2527

Filter 2:
[[0.5853 0.4393 0.4509 0.5445 0.5908 0.6346 0.6798 0.6962]
 [0.4095 0.3693 0.465  0.5431 0.5514 0.5665 0.5586 0.5385]
 [0.3349 0.4119 0.5192 0.5091 0.5072 0.4706 0.3835 0.3036]
 [0.4388 0.496  0.5057 0.5022 0.4989 0.3881 0.264  0.1502]
 [0.4965 0.5155 0.5123 0.506  0.4935 0.2987 0.2481 0.1895]
 [0.5465 0.5495 0.5297 0.5203 0.489  0.2895 0.3112 0.3525]
 [0.5717 0.5599 0.5515 0.542

In [1]:
import numpy as np

# Your input array
# input_array = np.array(
#     [
#      [ [0.26775], [0.1905], [0.11325], [0.18825], [0.202], [0.21775], [0.241],[0.263  ]],
#      [ [0.1795], [0.074], [0.167], [0.177], [0.17675], [0.1765], [0.1765], [0.168]],
#      [ [0.04725], [0.1705], [0.17325], [0.17325], [0.173], [0.173], [0.1495], [0.05425]],
#      [ [0.1335], [0.17175], [0.17075], [0.17025], [0.16975], [0.17025], [0.07425], [0.06175]],
#      [[0.13875], [0.1775], [0.1745], [0.17175], [0.16925], [0.16175], [0.02275], [0.07025]],
#      [ [0.19775], [0.18575], [0.18225], [0.179], [0.17575], [0.15475], [0.024], [0.15025]],
#      [[0.20225], [0.19475], [0.1905], [0.187], [0.18325], [0.147], [0.15325], [0.202]],
#      [[0.19975], [0.1995], [0.198], [0.19575], [0.19225], [0.19425], [0.199], [0.19875]],
#      ]
# )


# input_array=np.array(
#     [
#      [[ 0.1055], [-0.6441], [-0.1679]],       
#      [[-0.5026],[ -0.3969],  [0.2386]],
#      [[0.1918], [-0.4058],  [0.0865]]
#  ])


# input_array=np.array(
# [
#     [[-1.401e-01], [-3.163e-01], [-3.110e-01]],
#     [[-3.812e-01], [-9.260e-01], [-8.991e-01]],
#  [[ 8.000e-04],[-3.196e-01 ],[-6.684e-01]]
# ])



Filtro1=np.array([
 [-0.7275,  0.0826 , 0.1858],
 [-0.8432 ,-0.1808, -0.2278],
 [-0.5694,  0.1523 ,-0.4266]]
)
Filtro2=np.array([
[ 0.3942,  0.6029,  0.3215],
 [-0.3871, -0.1683,  0.0012],
 [-0.5312, -0.5164, -0.0725]]

)
Filtro3=np.array([
[ 0.7717 , 0.6768 , 0.5885],
 [ 0.8212 , 0.1071 ,-0.1187],
 [ 0.5252 , 0.3935 , 0.514 ]]
)


# Q1.7 conversion function

def float_to_q1_7_hex(value):
    scaled = int(round(value * 128))
    scaled = max(-128, min(127, scaled))
    if scaled < 0:
        scaled = (1 << 8) + scaled
    return f"{scaled:02X}"


def float_to_q1_17_hex(value):
    scaled = int(round(value * 2**15))
    scaled = max(-2**15, min(2**15-1, scaled))
    if scaled < 0:
        scaled = (1 << 16) + scaled
    return f"{scaled:02X}"

def float_to_q1_35_hex(value):
    scaled = int(round(value * 2**33))
    scaled = max(-2*33, min(2**33-1, scaled))
    if scaled < 0:
        scaled = (1 << 34) + scaled
    return f"{scaled:02X}"



flat1 = Filtro1.flatten()
flat2 = Filtro2.flatten()
flat3 = Filtro3.flatten()
hex_row1 = [float_to_q1_7_hex(val) for val in flat1]
hex_row2 = [float_to_q1_7_hex(val) for val in flat2]
hex_row3 = [float_to_q1_7_hex(val) for val in flat3]
# Print as a single line
print("Capa 1")
print("Filtro 1")
print(" ".join(hex_row1))
print("Bias 1")
print(float_to_q1_17_hex (0.4447))
print(" ".join(hex_row2))
print("Bias 2")
print(float_to_q1_17_hex (0.0624))
print(" ".join(hex_row3))
print("Bias 3")
print(float_to_q1_17_hex (-0.5740))



biases2 = [0.2922,-0.1406,0.2046,0.4010]

print("Capa 2\n")
print("Bias F1: ",float_to_q1_35_hex(biases2[0]),"\n")
print("Bias F2: ",float_to_q1_35_hex(biases2[1]),"\n")
print("Bias F3: ",float_to_q1_35_hex(biases2[2]),"\n")
print("Bias F4: ",float_to_q1_35_hex(biases2[3]),"\n")

Capa 1
Filtro 1
A3 0B 18 94 E9 E3 B7 13 C9
Bias 1
38EC
32 4D 29 CE EA 00 BC BE F7
Bias 2
7FD
63 57 4B 69 0E F1 43 32 42
Bias 3
B687
Capa 2

Bias F1:  959B3D08 

Bias F2:  3FFFFFFBE 

Bias F3:  68C154CA 

Bias F4:  CD4FDF3B 



In [ ]:

def float_to_q1_17_hex(value):
    scaled = int(round(value * 2**15))
    scaled = max(-2**15, min(2**15-1, scaled))
    if scaled < 0:
        scaled = (1 << 16) + scaled
    return f"{scaled:02X}"

def float_to_q1_31_hex(value):
    scaled = int(round(value * 2**31))
    scaled = max(-2**31, min(2**31-1, scaled))
    if scaled < 0:
        scaled = (1 << 32) + scaled
    return f"{scaled:02X}"


Filtro1=np.array([[ 0.4866 , 0.4649 , 0.4341],
 [ 0.2393 , 0.1499 ,-0.0584],
 [ 0.6413,  0.0337 , 0.3751]]
)
Filtro2=np.array([
[ 0.6356 , 0.2375 , 0.2634],
 [ 0.4743 ,-0.0459 ,-0.0642],
 [-0.     , 0.1915  ,0.159 ],]

)
Filtro3=np.array([
    [ 0.1552 , 0.0672 , 0.2108],
 [-0.2419, -0.3976 ,-0.1834],
 [-0.6534 ,-0.5284, -0.3189]]
)
flat1 = Filtro1.flatten()
flat2 = Filtro2.flatten()
flat3 = Filtro3.flatten()
hex_row1 = [float_to_q1_17_hex(val) for val in flat1]
hex_row2 = [float_to_q1_17_hex(val) for val in flat2]
hex_row3 = [float_to_q1_17_hex(val) for val in flat3]

print("Filtro 1")
print(" ".join(hex_row1))
print(" ".join(hex_row2))
print(" ".join(hex_row3))


print("Bias 1")
print(float_to_q1_31_hex ( 0.2922))
print("\n")
print(float_to_q1_31_hex ( -0.1406))
print("\n")
print(float_to_q1_31_hex ( 0.2046))
print("\n")
print(float_to_q1_31_hex ( 0.4010))

# se ponen de derecha a izquierda en el filtro , puedes tomar filtro 1 como referencia 
# Ultimo elemento de la linea va al primero del filtro xd
# los filtros van  

Filtro 1
3E49 3B82 3791 1EA1 1330 F886 5216 450 3003
515B 1E66 21B7 3CB6 FA20 F7C8 00 1883 145A
13DE 89A 1AFB E109 CD1B E886 AC5D BC5D D72E
Bias 1
2566CF42
